version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    image: unga62/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: unga62/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    container_name: foodgram-proxy
    env_file: .env
    image: unga62/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - media:/app/media/
      - static:/staticfiles/
    depends_on:
      - backend
      - frontend