# Generated by Django 3.2.3 on 2024-08-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shortlinkrecipes',
            name='Unique recipes in ShortLinkRecipes',
        ),
    ]
