# Generated by Django 3.2.3 on 2024-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_shortlinkrecipes_unique recipes in shortlinkrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkrecipes',
            name='full_link',
            field=models.URLField(),
        ),
    ]
