# Generated by Django 3.2.3 on 2024-08-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shortlinkrecipes_full_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkrecipes',
            name='full_link',
            field=models.URLField(unique=True),
        ),
    ]
